### ISSUE TITLE
Adapt for moving of parent project

### ISSUE THREAD

**Issue by discordier** [phpcq/plugin-phpcs#5]
According to https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

The repo has moved here: https://github.com/PHPCSStandards/PHP_CodeSniffer

We should add this as new source for upcoming versions.

**Comment by dmolineus** [comment]
> For Composer users, nothing changes.
>
>    In contrast to earlier information, the squizlabs/php_codesniffer package now points to the new repository and everything will continue to work as before.

https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0

**Comment by discordier** [comment]
Apparently, all 2.0 and 3.0 releases have been moved over to the new repository.

We still have to change the source repo in `phpcq-plugin.json`, as otherwise we won't track it.

**Comment by discordier** [comment]
Has been released as 1.1.1
